apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: github-action
  labels:
    app: my-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 888553893386.dkr.ecr.ap-southeast-1.amazonaws.com/lab-ecr-repo:latest  
        ports:
        - containerPort: 8080
